# Generated by Django 5.1.15 on 2026-08-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticsauditlog_legacy_postgres_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsauditlog',
            name='legacy_postgres_id',
        ),
    ]
