# Generated by Django 5.1.15 on 2026-08-25 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('github_path', models.CharField(blank=True, max_length=500, null=True)),
                ('github_sha', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PROCESANDO', 'Procesando'), ('LISTO', 'Listo'), ('ERROR', 'Error')], default='LISTO', max_length=15)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', models.JSONField()),
                ('page_number', models.PositiveIntegerField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='assistant.knowledgedocument')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
            },
        ),
    ]
