# Generated by Django 5.1.15 on 2026-08-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
