# Generated by Django 5.1.15 on 2026-08-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_documentchunk_legacy_postgres_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='legacy_postgres_id',
        ),
    ]
