# Generated by Django 5.1.15 on 2026-08-13 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PLANIFICACION', 'Planificacion'), ('EN_EJECUCION', 'En Ejecucion'), ('EN_REVISION', 'En Revision'), ('SUSPENDIDO', 'Suspendido'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('priority', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=10)),
                ('area', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('observations', models.TextField(blank=True, default='')),
                ('start_date', models.DateTimeField()),
                ('target_date', models.DateTimeField()),
                ('target_time_hours', models.FloatField()),
                ('real_hours', models.FloatField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('CREADO', 'Creado'), ('ACTUALIZADO', 'Actualizado'), ('PARTICIPANTE_AGREGADO', 'Participante Agregado'), ('PARTICIPANTE_ELIMINADO', 'Participante Eliminado'), ('RESPONSABLE_CAMBIADO', 'Responsable Cambiado'), ('ESTADO_CAMBIADO', 'Estado Cambiado'), ('FASE_AGREGADA', 'Fase Agregada'), ('FASE_ACTUALIZADA', 'Fase Actualizada'), ('FASE_ELIMINADA', 'Fase Eliminada'), ('COMENTARIO_AGREGADO', 'Comentario Agregado'), ('ACTIVIDAD_REGISTRADA', 'Actividad Registrada'), ('DOCUMENTO_AGREGADO', 'Documento Agregado'), ('ELIMINADO', 'Eliminado'), ('RESTAURADO', 'Restaurado')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['deleted_at'], name='projects_pr_deleted_4c0d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='projecthistory',
            index=models.Index(fields=['project', 'created_at'], name='projects_pr_project_fee558_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectparticipant',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_participant'),
        ),
    ]
