# Generated by Django 5.1.15 on 2026-08-13 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectphase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('PDF', 'Pdf'), ('EXCEL', 'Excel'), ('WORD', 'Word'), ('IMAGEN', 'Imagen'), ('CORREO', 'Correo'), ('ACTA', 'Acta'), ('OTRO', 'Otro')], default='OTRO', max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('file_data', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('previous_version_id', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project'], name='projects_pr_project_65ce8a_idx')],
            },
        ),
    ]
