# Generated by Django 5.1.15 on 2026-08-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectactivity_projectdocument_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectparticipant',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
