# Generated by Django 5.1.15 on 2026-08-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_legacy_postgres_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='projectactivity',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='projectdocument',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='projectparticipant',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='legacy_postgres_id',
        ),
    ]
