# Generated by Django 5.1.15 on 2026-08-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
