# Generated by Django 5.1.15 on 2026-08-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_legacy_postgres_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kpi_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
