# Generated by Django 5.1.15 on 2026-08-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_kpi_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_consent_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='data_consent_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
