# Generated by Django 5.1.15 on 2026-08-20 20:02

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_data_consent_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="badges",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="view_preferences",
            field=models.JSONField(blank=True, default=apps.users.models._default_view_preferences),
        ),
    ]
