# Generated by Django 5.1.15 on 2026-08-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_badges_view_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("LIGHT", "Light"), ("DARK", "Dark")], default="LIGHT", max_length=5
            ),
        ),
    ]
