# Generated by Django 5.1.15 on 2026-08-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='legacy_postgres_id',
        ),
    ]
