# Generated by Django 5.1.15 on 2026-09-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='previous_refresh_token_jti',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='session',
            name='rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
