# Generated by Django 5.1.15 on 2026-09-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modulepermission",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("usuarios.ver", "Ver usuarios"),
                    ("usuarios.crear", "Crear usuarios"),
                    ("usuarios.editar", "Editar usuarios y su asignación de roles/permisos"),
                    (
                        "usuarios.deshabilitar",
                        "Habilitar, deshabilitar, bloquear y desbloquear usuarios",
                    ),
                    (
                        "usuarios.restablecer_password",
                        "Enviar enlace de restablecimiento, forzar cambio de contraseña en el próximo inicio o cerrar sesiones activas de un usuario",
                    ),
                    ("roles.ver", "Ver roles y el catálogo de permisos"),
                    ("roles.editar", "Crear, editar y eliminar roles"),
                    (
                        "permisos.ver",
                        "Ver el catálogo de permisos y a qué módulo pertenece cada uno",
                    ),
                    ("configuracion.ver", "Ver configuración del sistema"),
                    ("configuracion.editar", "Editar configuración del sistema"),
                    ("auditoria.ver", "Ver el registro de auditoría"),
                    (
                        "auditoria.ver_detalle",
                        "Ver el detalle (valores anteriores y nuevos) de un evento",
                    ),
                    ("auditoria.ver_ubicacion", "Ver la ubicación aproximada asociada a un evento"),
                    ("auditoria.exportar", "Exportar el registro de auditoría"),
                    (
                        "tareas.regularizar",
                        "Regularizar en bloque Tiempo Objetivo/Fecha Fin y ver pendientes de regularización",
                    ),
                    ("tareas.cerrar_mes", "Cerrar el mes de tareas del equipo"),
                    ("reportes.ver", "Ver y generar reportes ejecutivos"),
                    ("equipo.ver", "Ver el equipo (subordinados) y sus tareas"),
                    ("reuniones.crear", "Crear y programar reuniones"),
                    ("mejora_continua.revisar", "Revisar ideas y cambiar su estado"),
                    ("base_conocimiento.ver", "Ver la base de conocimiento y consultarla vía NOVA"),
                    (
                        "base_conocimiento.gestionar",
                        "Subir y eliminar documentos de la base de conocimiento",
                    ),
                    ("inteligencia_preventiva.ver", "Ver el Índice de Riesgo Operativo del equipo"),
                    ("proyectos.crear", "Crear un proyecto"),
                    (
                        "escritorio_digital.usar",
                        "Usar el Escritorio Digital (notas y recordatorios)",
                    ),
                    ("comunicados.gestionar", "Publicar y eliminar comunicados"),
                ],
            },
        ),
    ]
