# Generated by Django 5.1.15 on 2026-08-07 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_activityreason_taskactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date_approval_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('MODIFICADA', 'Modificada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='target_time_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='target_time_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EndDateAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.PositiveBigIntegerField(db_index=True)),
                ('user_role', models.CharField(blank=True, default='', max_length=50)),
                ('action', models.CharField(choices=[('PROPUESTA', 'Propuesta'), ('APROBADA', 'Aprobada'), ('MODIFICADA', 'Modificada'), ('RECHAZADA', 'Rechazada')], max_length=15)),
                ('previous_value', models.DateTimeField(blank=True, null=True)),
                ('new_value', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetTimeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.PositiveBigIntegerField(db_index=True)),
                ('user_role', models.CharField(blank=True, default='', max_length=50)),
                ('previous_value', models.FloatField(blank=True, null=True)),
                ('new_value', models.FloatField()),
                ('reason', models.CharField(choices=[('PROCEDIMIENTO_ESTANDAR', 'Procedimiento Estandar'), ('COMPLEJIDAD_DETECTADA', 'Complejidad Detectada'), ('CAMBIO_ALCANCE', 'Cambio Alcance'), ('REVISION_LIDER', 'Revision Lider'), ('OTRO', 'Otro')], max_length=30)),
                ('reason_detail', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
