# Generated by Django 5.1.15 on 2026-08-07 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_end_date_approval_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("closed_at", models.DateTimeField(auto_now_add=True)),
                ("cutoff_date", models.DateTimeField()),
                (
                    "closure_type",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("EARLY", "Early"), ("MANUAL", "Manual")],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                ("calendar_days_total", models.PositiveSmallIntegerField()),
                ("calendar_days_considered", models.PositiveSmallIntegerField()),
                ("working_days_considered", models.PositiveSmallIntegerField()),
                ("working_hours_considered", models.FloatField()),
                ("total_tasks", models.PositiveIntegerField()),
                ("completed_tasks", models.PositiveIntegerField()),
                ("summary", models.JSONField()),
                ("corrections", models.JSONField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closed_months",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("month", "year"), name="unique_month_year_closure"
                    )
                ],
            },
        ),
    ]
