# Generated by Django 5.1.15 on 2026-08-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskactivity_admin_comment_taskactivity_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityauditlog',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='activitycomment',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='activityreason',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='enddateauditlog',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='monthclosure',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='targettimeauditlog',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='taskcommentview',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
