# Generated by Django 5.1.15 on 2026-08-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_activityauditlog_legacy_postgres_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityauditlog',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='activitycomment',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='activityreason',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='enddateauditlog',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='monthclosure',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='targettimeauditlog',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='taskactivity',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='taskcommentview',
            name='legacy_postgres_id',
        ),
    ]
