# Generated by Django 5.1.15 on 2026-10-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_activityauditlog_legacy_postgres_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='successor_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
