# Generated by Django 5.1.15 on 2026-08-20 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=64)),
                ('module_label', models.CharField(max_length=100)),
                ('operation', models.CharField(choices=[('MOVE_TO_TRASH', 'Move To Trash'), ('RESTORE', 'Restore'), ('DELETE_PERMANENTLY', 'Delete Permanently'), ('PURGE_EXPIRED', 'Purge Expired')], max_length=20)),
                ('origin', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='recovery_re_entity__5cd073_idx'), models.Index(fields=['created_at'], name='recovery_re_created_c663b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecoveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=64)),
                ('entity_label', models.CharField(blank=True, max_length=255, null=True)),
                ('module_label', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESTORED', 'Restored'), ('PURGED', 'Purged')], default='ACTIVE', max_length=15)),
                ('deleted_at', models.DateTimeField()),
                ('retention_hours', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('purge_origin', models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='recovery_re_entity__fda512_idx'), models.Index(fields=['status', 'expires_at'], name='recovery_re_status_20df41_idx')],
            },
        ),
    ]
