# Generated by Django 5.1.15 on 2026-08-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0002_recoveryauditlog_legacy_postgres_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoveryauditlog',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='recoveryitem',
            name='legacy_postgres_id',
        ),
    ]
