# Generated by Django 5.1.15 on 2026-08-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_datapurgelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='leaverecord',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='specialstatus',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='systemconfighistory',
            name='legacy_postgres_id',
        ),
    ]
