# Generated by Django 5.1.15 on 2026-09-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0005_remove_holiday_legacy_postgres_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemconfighistory",
            name="value",
            field=models.TextField(),
        ),
    ]
