# Generated by Django 5.1.15 on 2026-08-18 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveReportAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=40)),
                ('action', models.CharField(choices=[('generated', 'Generated'), ('generation_failed', 'Generation Failed'), ('nova_degraded', 'Nova Degraded'), ('viewed', 'Viewed'), ('exported_pdf', 'Exported Pdf'), ('exported_excel', 'Exported Excel'), ('legacy_migrated', 'Legacy Migrated')], max_length=20)),
                ('step', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_corte', models.DateTimeField(blank=True, null=True)),
                ('filters_applied', models.JSONField(blank=True, null=True)),
                ('collaborator_count', models.PositiveIntegerField(blank=True, null=True)),
                ('generation_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('analytics_engine_version', models.CharField(blank=True, max_length=20, null=True)),
                ('formula_set_version', models.CharField(blank=True, max_length=20, null=True)),
                ('nexo_version', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['report_id'], name='reports_exe_report__d6babe_idx'), models.Index(fields=['user', 'created_at'], name='reports_exe_user_id_9da24e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=40, unique=True)),
                ('type', models.CharField(choices=[('MENSUAL', 'Mensual'), ('RANGO_MESES', 'Rango Meses'), ('RANGO_PERSONALIZADO', 'Rango Personalizado')], max_length=25)),
                ('scope', models.CharField(choices=[('JEFE', 'Jefe'), ('COORDINADOR', 'Coordinador')], max_length=15)),
                ('origin', models.CharField(choices=[('GENERATED', 'Generated'), ('LEGACY_MIGRATION', 'Legacy Migration')], default='GENERATED', max_length=20)),
                ('integrity_flag', models.CharField(choices=[('FULL', 'Full'), ('PARTIAL', 'Partial')], default='FULL', max_length=10)),
                ('legacy_monthly_report_id', models.CharField(blank=True, max_length=40, null=True)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField()),
                ('period_label', models.CharField(max_length=255)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('fecha_corte', models.DateTimeField()),
                ('period_status', models.CharField(choices=[('EN_CURSO', 'En Curso'), ('CERRADO', 'Cerrado'), ('HISTORICO', 'Historico')], max_length=15)),
                ('filters', models.JSONField()),
                ('collaborator_ids', models.JSONField(blank=True, default=list)),
                ('collaborator_count', models.PositiveIntegerField(default=0)),
                ('analytics_engine_version', models.CharField(max_length=20)),
                ('formula_set_version', models.CharField(max_length=20)),
                ('reporting_engine_version', models.CharField(max_length=20)),
                ('nexo_version', models.CharField(max_length=20)),
                ('data', models.JSONField()),
                ('nova', models.JSONField(blank=True, null=True)),
                ('nova_degraded', models.BooleanField(default=False)),
                ('data_quality', models.JSONField()),
                ('generation_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['generated_by', 'created_at'], name='reports_exe_generat_a13b07_idx'), models.Index(fields=['type', 'period_start', 'period_end'], name='reports_exe_type_f69ec5_idx'), models.Index(fields=['origin'], name='reports_exe_origin_6256e7_idx')],
            },
        ),
    ]
