# Generated by Django 5.1.15 on 2026-08-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveReportIntegrityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=40)),
                ('field_path', models.CharField(max_length=255)),
                ('expected_value', models.FloatField()),
                ('actual_value', models.FloatField()),
                ('source', models.CharField(choices=[('kpis_team', 'Kpis Team')], default='kpis_team', max_length=20)),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['report_id'], name='reports_exe_report__5685f5_idx'), models.Index(fields=['detected_at'], name='reports_exe_detecte_4f3c07_idx')],
            },
        ),
    ]
