# Generated by Django 5.1.15 on 2026-08-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_monthlyreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executivereportauditlog',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='executivereportsnapshot',
            name='legacy_postgres_id',
        ),
    ]
