# Generated by Django 5.1.15 on 2026-08-17 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=500)),
                ('priority', models.CharField(choices=[('INFORMACION', 'Información'), ('RECORDATORIO', 'Recordatorio'), ('IMPORTANTE', 'Importante'), ('URGENTE', 'Urgente')], default='INFORMACION', max_length=20)),
                ('color', models.CharField(choices=[('AMARILLO', 'Amarillo'), ('ROSADO', 'Rosado'), ('CELESTE', 'Celeste'), ('VERDE', 'Verde'), ('NARANJA', 'Naranja'), ('LILA', 'Lila')], default='AMARILLO', max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_notes', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeskNoteReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='desk.desknote')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeskAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=20)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('EDITED', 'Edited'), ('READ', 'Read'), ('PINNED', 'Pinned'), ('UNPINNED', 'Unpinned'), ('ARCHIVED', 'Archived'), ('UNARCHIVED', 'Unarchived'), ('DELETED', 'Deleted'), ('CONVERTED_TO_TASK', 'Converted To Task'), ('CONVERTED_TO_REMINDER', 'Converted To Reminder'), ('PRIORITY_CHANGED', 'Priority Changed'), ('POSTPONED', 'Postponed'), ('COMPLETED', 'Completed'), ('REOPENED', 'Reopened'), ('REPLIED', 'Replied')], max_length=30)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='desk_deskau_entity__90e42d_idx'), models.Index(fields=['user', 'created_at'], name='desk_deskau_user_id_3f1123_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='desknote',
            index=models.Index(fields=['recipient', 'archived', 'created_at'], name='desk_deskno_recipie_4446e2_idx'),
        ),
        migrations.AddIndex(
            model_name='desknote',
            index=models.Index(fields=['sender', 'created_at'], name='desk_deskno_sender__d96c89_idx'),
        ),
        migrations.AddIndex(
            model_name='desknotereply',
            index=models.Index(fields=['note', 'created_at'], name='desk_deskno_note_id_916233_idx'),
        ),
    ]
