# Generated by Django 5.1.15 on 2026-08-17 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_personalreminder'),
        ('tasks', '0005_taskactivity_admin_comment_taskactivity_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalreminder',
            name='converted_to_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='personalreminder',
            name='converted_to_task_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
