# Generated by Django 5.1.15 on 2026-08-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_personalreminder_converted_to_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desknote',
            name='attachment_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desknote',
            name='attachment_mime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='desknote',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
