# Generated by Django 5.1.15 on 2026-08-17 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0004_desknote_attachment_data_desknote_attachment_mime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desknote',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desknote',
            name='converted_to_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='desk.personalreminder'),
        ),
        migrations.AddField(
            model_name='personalreminder',
            name='attachment_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalreminder',
            name='attachment_mime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalreminder',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
