# Generated by Django 5.1.15 on 2026-08-20 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0005_desknote_converted_at_desknote_converted_to_reminder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='desknote',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='desknote',
            index=models.Index(fields=['deleted_at'], name='desk_deskno_deleted_261ed1_idx'),
        ),
    ]
