# Generated by Django 5.1.15 on 2026-08-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0006_desknote_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskauditlog',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='desknote',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='desknotereply',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='personalreminder',
            name='legacy_postgres_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
