# Generated by Django 5.1.15 on 2026-08-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0007_deskauditlog_legacy_postgres_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deskauditlog',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='desknote',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='desknotereply',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='personalreminder',
            name='legacy_postgres_id',
        ),
    ]
