# Generated by Django 5.1.15 on 2026-08-07 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleNotificationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group')),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_group', 'target_group'), name='unique_notification_target_pair')],
            },
        ),
        migrations.CreateModel(
            name='RoleVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group')),
                ('visible_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('viewer_group', 'visible_group'), name='unique_role_visibility_pair')],
            },
        ),
    ]
