# Generated by Django 5.1.15 on 2026-08-19 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo')], max_length=10)),
                ('status', models.CharField(choices=[('PROPUESTA', 'Propuesta'), ('EN_REVISION', 'En Revision'), ('APROBADA', 'Aprobada'), ('EN_DESARROLLO', 'En Desarrollo'), ('EN_PRUEBAS', 'En Pruebas'), ('IMPLEMENTADA', 'Implementada'), ('RECHAZADA', 'Rechazada')], default='PROPUESTA', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_mime', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_data', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_ideas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idea_votes', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ideas.improvementidea')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(choices=[('PROPUESTA', 'Propuesta'), ('EN_REVISION', 'En Revision'), ('APROBADA', 'Aprobada'), ('EN_DESARROLLO', 'En Desarrollo'), ('EN_PRUEBAS', 'En Pruebas'), ('IMPLEMENTADA', 'Implementada'), ('RECHAZADA', 'Rechazada')], max_length=20)),
                ('to_status', models.CharField(choices=[('PROPUESTA', 'Propuesta'), ('EN_REVISION', 'En Revision'), ('APROBADA', 'Aprobada'), ('EN_DESARROLLO', 'En Desarrollo'), ('EN_PRUEBAS', 'En Pruebas'), ('IMPLEMENTADA', 'Implementada'), ('RECHAZADA', 'Rechazada')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idea_status_changes', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ideas.improvementidea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='improvementidea',
            index=models.Index(fields=['author'], name='ideas_impro_author__7cc6b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='ideavote',
            constraint=models.UniqueConstraint(fields=('idea', 'user'), name='unique_idea_vote'),
        ),
    ]
