# Generated by Django 5.1.15 on 2026-08-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_ideastatushistory_legacy_postgres_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideastatushistory',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='ideavote',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='improvementidea',
            name='legacy_postgres_id',
        ),
    ]
