# Generated by Django 5.1.15 on 2026-08-19 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('meeting_date', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=50, null=True)),
                ('zoom_join_url', models.TextField(blank=True, null=True)),
                ('zoom_password', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada')], default='PROGRAMADA', max_length=15)),
                ('otter_invited', models.BooleanField(default=False)),
                ('otter_summary', models.TextField(blank=True, null=True)),
                ('otter_transcript_url', models.TextField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingInvitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['host'], name='meetings_me_host_id_dc89dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetinginvitee',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='unique_meeting_invitee'),
        ),
    ]
