# Generated by Django 5.1.15 on 2026-08-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_legacy_postgres_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='legacy_postgres_id',
        ),
        migrations.RemoveField(
            model_name='meetinginvitee',
            name='legacy_postgres_id',
        ),
    ]
